### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Urbaeexyz** [sindresorhus/parse-ms#13]
i'm a newbie
so sorry if i ask this stupid things

how can to countdown hours for use parse-ms?

like this

const parseMilliseconds = require('parse-ms');

parseMilliseconds(1337000001);
/*
{
	days: 15,
	hours: 11,
	minutes: 23,
	seconds: 20,
	milliseconds: 1,
	microseconds: 0,
	nanoseconds: 0
}

how can you get this number = 1337000001

**Comment by sindresorhus** [comment]
I'm not entirely sure what you're asking, but it sound like you're looking for https://github.com/sindresorhus/to-milliseconds
