### ISSUE TITLE
Should support month and years

### ISSUE THREAD

**Issue by lykmapipo** [sindresorhus/parse-ms#2]
```js
var parseMs = require("parse-ms");
parseMs(133700000000);

{
days: 1547
hours: 10
milliseconds: 0
minutes: 53
seconds: 20
}
```

**Comment by sindresorhus** [comment]
Same answer as https://github.com/sindresorhus/pretty-ms/issues/16#issuecomment-315037501

**Comment by sindresorhus** [comment]
Closing as we can't accurately calculate months and years without defining a set point in time and that's outside the scope of this module. The year addition can still happen in the `pretty-ms` package though.
