### ISSUE TITLE
Version 2.0.0 breaks karma test runner

### ISSUE THREAD

**Issue by mikkelwf** [sindresorhus/parse-ms#6]
I think its because phantomjs (2.1.1) only support ES5, and not ES6...

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser or PhantomJS. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
