### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by hanwenbo** [sindresorhus/parse-ms#8]
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 
        ./node_modules/parse-ms/index.js:2

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
